pipeline {

    tools {
        maven "maven"
        jdk "jdk17"
    }

    stages {
        stage('Build') {
            steps {
                dir("/var/lib/jenkins/workspace/maven-project/my-app") {
                sh 'mvn clean package'
                }
            
            }
        }
     }
}
