pipeline {
    agent any
    stages {
        stage('maven clean and validate'){
            steps{
                dir("/var/lib/jenkins/workspace/sample-piepline/my-app") {
                // #script execute
                // multiple commands script
                sh '''
                mvn clean
                mvn validate
                '''
                //Single command script
                // sh 'mvn clean'
                }
            }
        }
        stage('maven compile and test'){
            steps{
                dir("/var/lib/jenkins/workspace/sample-piepline/my-app") {
                sh '''
                mvn compile
                mvn test
                '''                    
                }
            }
        }
        stage('maven package'){
            steps{
                dir("/var/lib/jenkins/workspace/sample-piepline/my-app") {
                sh 'mvn package' 
                }                 
            }
        }
    }
}
