pipeline {
    agent any;
    stages {
        stage('Build') {
            steps {
                dir("/var/lib/jenkins/workspace/maven-project/my-app") {
                sh 'mvn clean package'
                }
            
            }
        }
     }
}
